apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/monitoring/portainer
  prune: true
  sourceRef:
    kind: GitRepository
    name: azure-hybrid-boilerplate
    namespace: flux-system
  targetNamespace: portainer
  createNamespace: true
